"""
Multi-Sensor Data Trimming and Alignment Pipeline.

Description:
    This script orchestrates the trimming and filtering of EEG and EMG data 
    based on a session manifest generated during the file-matching stage. 
    It ensures that raw sensor data is aligned with the action/label 
    timestamps and exports cleaned CSV files for further analysis.

Author: Kartikay Naswa (@kartikaynaswa)

Preconditions:
    - A 'session_manifest_with_errors.csv' exists (generated by Filematching.py).
    - Raw EEG (.txt) and EMG (.csv) files are accessible at the paths listed in the manifest.
    - Modules 'eegtrim' and 'emgtrim' are available in the search path.

Postconditions:
    - Creates a 'data/trimmed' directory if it doesn't exist.
    - Generates trimmed/filtered EEG and EMG CSV files per session.
"""

import logging
from pathlib import Path
import pandas as pd

from eegtrim import process_eeg as trim_eeg
from emgtrim import process_emg as trim_emg

# --- Configuration ---
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# Paths for input manifest and output data
MANIFEST_PATH = Path('./data/synchronized/session_manifest_with_errors.csv')
OUTPUT_TRIMMED_DIR = Path('./data/trimmed')


def process_session(manifest_row: pd.Series) -> None:
    """Synchronizes and trims sensor data for a single session entry.

    Args:
        manifest_row: A row from the manifest DataFrame containing file paths.
    """
    action_path = manifest_row['Action_File']
    eeg_path = manifest_row['EEG_File']
    emg_path = manifest_row['EMG_File']

    # Extract filename without extension to use as a session identifier
    session_id = Path(action_path).stem

    # Construct output file paths
    eeg_filtered_path = OUTPUT_TRIMMED_DIR / f"eeg_filtered_{session_id}.csv"
    eeg_trimmed_path = OUTPUT_TRIMMED_DIR / f"eeg_trimmed_{session_id}.csv"
    emg_trimmed_path = OUTPUT_TRIMMED_DIR / f"emg_trimmed_{session_id}.csv"

    # Process EEG data if available
    if eeg_path and eeg_path != 'null':
        try:
            trim_eeg(
                eeg_path=eeg_path,
                action_path=action_path,
                filtered_output_path=str(eeg_filtered_path),
                trimmed_output_path=str(eeg_trimmed_path)
            )
        except Exception as e:
            logger.error(f"Failed to trim EEG for {session_id}: {e}")

    # Process EMG data if available
    if emg_path and emg_path != 'null':
        try:
            trim_emg(
                myo_path=emg_path,
                action_path=action_path,
                output_path=str(emg_trimmed_path)
            )
        except Exception as e:
            logger.error(f"Failed to trim EMG for {session_id}: {e}")


def main() -> None:
    """Loads the session manifest and executes the trimming pipeline."""
    if not MANIFEST_PATH.exists():
        logger.error(f"Manifest not found: {MANIFEST_PATH}")
        return

    OUTPUT_TRIMMED_DIR.mkdir(parents=True, exist_ok=True)

    logger.info(f"Loading manifest from {MANIFEST_PATH}...")
    df_manifest = pd.read_csv(MANIFEST_PATH)

    logger.info(f"Found {len(df_manifest)} sessions. Starting processing...")

    for _, row in df_manifest.iterrows():
        logger.info(f"--- Processing: {row['Action_File']} ---")
        process_session(row)

    logger.info("Pipeline execution completed.")


if __name__ == "__main__":
    main()